
CREATE DATABASE IF NOT EXISTS dairy_db_v3;
USE dairy_db_v3;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS dairies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  logo_path VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dairy_id INT NOT NULL,
  name VARCHAR(200) NOT NULL,
  unit VARCHAR(50) DEFAULT 'litre',
  cost_price DECIMAL(10,2) NOT NULL,
  sell_price DECIMAL(10,2) NOT NULL,
  min_stock DECIMAL(10,2) DEFAULT 0,
  current_stock DECIMAL(12,2) DEFAULT 0,
  FOREIGN KEY (dairy_id) REFERENCES dairies(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_in (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dairy_id INT NOT NULL,
  product_id INT NOT NULL,
  qty DECIMAL(10,2) NOT NULL,
  cost_price DECIMAL(10,2) NOT NULL,
  date DATE NOT NULL,
  remarks VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  FOREIGN KEY (dairy_id) REFERENCES dairies(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sales (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dairy_id INT NOT NULL,
  product_id INT NOT NULL,
  qty DECIMAL(10,2) NOT NULL,
  selling_price DECIMAL(10,2) NOT NULL,
  date DATE NOT NULL,
  remarks VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  FOREIGN KEY (dairy_id) REFERENCES dairies(id) ON DELETE CASCADE
);
